### ISSUE TITLE
arn.split method failing 

### ISSUE THREAD

**Issue by gmmurugan** [tensult/cloud-reports#1]
{}
{}
{}
**TypeError: arn.split is not a function**
    at RolesWithoutExternalIDAnalyzer.getAccountID (C:\Users\work\cloud-reports\dist\analyzers\aws\iam\roles_without_external_id.js:99:24)
    at C:\Users\work\cloud-reports\dist\analyzers\aws\iam\roles_without_external_id.js:88:46
    at Array.map (<anonymous>)
    at RolesWithoutExternalIDAnalyzer.getRoleAccountsObject (C:\Users\work\cloud-reports\dist\analyzers\aws\iam\roles_without_external_id.js:86:12)
    at C:\Users\work\cloud-reports\dist\analyzers\aws\iam\roles_without_external_id.js:76:26
    at Array.map (<anonymous>)

![image](https://user-images.githubusercontent.com/48428/48736986-70c00900-ec12-11e8-9024-445daea227aa.png)

**Comment by koladilip** [comment]
@gmmurugan Thank you so much for reporting this issue, This was happening when IAM role as multiple trusted accounts. I have fixed this. Please try again.
