### ISSUE TITLE
Unhandled errors

### ISSUE THREAD

**Issue by gmmurugan** [tensult/cloud-reports#2]
Code Error 1:
```
arn:aws:elasticloadbalancing:eu-west-1:1222335566:loadbalancer/net/BastionNLB/xxxxxxx19f0cxxxxd
{}
{}
{}
**TypeError: Cannot read property 'filter' of undefined**
at UsersAccessKeysUnusedAnalyzer.analyze (C:\Users\work\cloud-reports\dist\analyzers\aws\iam\users_access_keys_unused.js:24:43)
at Object.analyze (C:\Users\work\cloud-reports\dist\analyze.js:17:29)
at C:\Users\work\cloud-reports\dist\scan.js:132:49
at step (C:\Users\work\cloud-reports\dist\scan.js:32:23)
at Object.next (C:\Users\work\cloud-reports\dist\scan.js:13:53)
at fulfilled (C:\Users\work\cloud-reports\dist\scan.js:4:58)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

Code Error 2 :

```
arn:aws:elasticloadbalancing:eu-west-1:12349052234:loadbalancer/net/BastionNLB/123456e19fabcdef
{}
{}
{}
**TypeError: Cannot read property 'LoggingEnabled' of undefined**
    at CloudTrailsBucketAccessLogsAnalyzer.analyze (/home/cloud-reports/dist/analyzers/aws/s3/bucket_access_logs.js:40:34)
    at Object.analyze (/home/cloud-reports/dist/analyze.js:17:29)
    at /home/cloud-reports/dist/scan.js:132:49
    at step (/home/cloud-reports/dist/scan.js:32:23)
    at Object.next (/home/cloud-reports/dist/scan.js:13:53)
    at fulfilled (/home/cloud-reports/dist/scan.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Runtime Exceptions: happens all over resources. its not breaking but need to handle in debug as its async and not sure which service its causing. Unauthorized error is happening because of services unavailability? or against what resources? its not clear

```
 message: 'The AWS Access Key Id needs a subscription for the service',
  code: 'OptInRequired',
  time: 2018-11-19T21:55:28.400Z,
  requestId: '1234556-8539-5755-9841-12324343434',
  statusCode: 403,
  retryable: false,

```
```
 'You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe.',
  code: 'OptInRequired',
  time: 2018-11-14T18:59:38.113Z,
  requestId: '123456-f105-4d75-8643-9b93d8f67157',
  statusCode: 401,
  retryable: false,
  retryDelay: 28.231563105015155 }
{ AuthFailure: AWS was not able to validate the provided access credentials
    at Request.extractError (/home/cloud-reports/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/home/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:109:20)

 [ERROR] { InvalidClientTokenId: The security token included in the request is invalid
    at Request.extractError (/Users/work/cloud-reports/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/Users/work/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at Request.emit (/Users/work/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/Users/work/cloud-reports/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/work/cloud-reports/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/work/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/work/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/work/cloud-reports/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/work/cloud-reports/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/work/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
  message: 'The security token included in the request is invalid',
  code: 'InvalidClientTokenId',
  time: 2018-11-13T15:44:09.368Z,
  requestId: '123445534-e75a-11e8-8100-db410eb6fa0b',
  statusCode: 403,
  retryable: false,

**Comment by koladilip** [comment]
@gmmurugan Thanks again, I have fixed these issues.
