### ISSUE TITLE
Cannot read property 'VpcId' of undefined

### ISSUE THREAD

**Issue by cloudgprabhu** [tensult/cloud-reports#40]
Hi, I have very restricted access, while generating pdf report I have the below error. Is that because of any permission issue? 

TypeError: Cannot read property 'VpcId' of undefined
    at DefaultVpcUsedRDSInstancesAnalyzer.analyze (D:\Users\ABCD\Documents\User\Scripts\cloud-reports\cloud-reports\dist\analyzers\aws\rds\default_vpcs_used.js:27:51)
    at Object.analyze (D:\Users\ABCD\Documents\User\Scripts\cloud-reports\cloud-reports\dist\analyze.js:17:31)
    at scan (D:\Users\ABCD\Documents\User\Scripts\cloud-reports\cloud-reports\dist\scan.js:84:43)

**Comment by Harshul1310** [comment]
Sir, I generated a pull request which has the package with error resolved.  request: rdsDefaultVpc

**Comment by cloudgprabhu** [comment]
was the issue fixed? I pulled and tried again but I have the issue still....

**Comment by koladilip** [comment]
We are working on fix and this is not yet merged. @forest-cloud

**Comment by koladilip** [comment]
@forest-cloud we have merged now, can you check now please?
