### ISSUE TITLE
Error: regionDetails.filter is not a function

### ISSUE THREAD

**Issue by cloudgprabhu** [tensult/cloud-reports#55]
I tried npm run scan -- --profile profilename -f pdf -i
encountering below error.

TypeError: regionDetails.filter is not a function
    at processReportData (D:\Users\USER\Documents\USER1\Scripts\cloud-reports\dist\reporters\pdf\html.js:14:51)
    at Object.generateHTML (D:\Users\USER\Documents\USER1\Scripts\cloud-reports\dist\reporters\pdf\html.js:39:18)
    at Object.generatePDF (D:\Users\USER\Documents\USER1\Scripts\cloud-reports\dist\reporters\pdf\index.js:46:26)
    at makeFileContents (D:\Users\USER\Documents\USER1\Scripts\cloud-reports\dist\scan.js:58:30)
    at scan (D:\Users\USER\Documents\USER1\Scripts\cloud-reports\dist\scan.js:95:38)

**Comment by koladilip** [comment]
Please do git pull and npm run build, I have added fix for this.

**Comment by cloudgprabhu** [comment]
the issue is not resolved...
when I try to export csv or if I use -i parameter, still I have error.
Only PDF full report is working well.

**Comment by koladilip** [comment]
I have added fix for csv also please check now.
