### ISSUE TITLE
failed UnauthorizedOperation: You are not authorized to perform this operation.

### ISSUE THREAD

**Issue by nmarchini** [tensult/cloud-reports#74]
I have setup an Amazon Linux 2 EC2 instance in AWS that have an IAM role that has the AWS managed policy for 'ReadOnlyAccess'. I have installed and built the software but get errors when I run the modules. 

I can run aws ec2 describe-instances and it returns all the instances in the current region. 

**Shell Error**
[root@ip-172-31-4-166 cloud-reports]# npm run scan -- --module ec2

> cloud-reports@1.4.1 scan /home/ec2-user/cloud-reports
> node dist/scan.js "--module" "ec2"

[ERROR] aws.ec2.EC2InstancesCollector failed UnauthorizedOperation: You are not authorized to perform this operation.
    at Request.extractError (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'You are not authorized to perform this operation.',
  code: 'UnauthorizedOperation',
  time: 2020-02-18T23:38:32.136Z,
  requestId: 'd2678875-0aff-4926-8c8b-e87f170cfd98',
  statusCode: 403,
  retryable: false,
  retryDelay: 52.10211392839121
}
[ERROR] aws.ec2.TerminationProtectionCollector failed UnauthorizedOperation: You are not authorized to perform this operation.
    at Request.extractError (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'You are not authorized to perform this operation.',
  code: 'UnauthorizedOperation',
  time: 2020-02-18T23:38:32.136Z,
  requestId: 'd2678875-0aff-4926-8c8b-e87f170cfd98',
  statusCode: 403,
  retryable: false,
  retryDelay: 52.10211392839121
}
[ERROR] aws.ec2.KeyPairsCollector failed UnauthorizedOperation: You are not authorized to perform this operation.
    at Request.extractError (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'You are not authorized to perform this operation.',
  code: 'UnauthorizedOperation',
  time: 2020-02-18T23:38:32.142Z,
  requestId: 'f028e566-ce54-4244-b7c1-2de319ba9ee4',
  statusCode: 403,
  retryable: false,
  retryDelay: 41.922081891271205
}
[ERROR] aws.ec2.SecurityGroupsCollector failed UnauthorizedOperation: You are not authorized to perform this operation.
    at Request.extractError (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'You are not authorized to perform this operation.',
  code: 'UnauthorizedOperation',
  time: 2020-02-18T23:38:32.198Z,
  requestId: 'ec686a8c-f975-4436-b9af-fb8a29e8f78e',
  statusCode: 403,
  retryable: false,
  retryDelay: 39.02717297224005
}
[ERROR] aws.ec2.EC2ReservedInstancesCollector failed UnauthorizedOperation: You are not authorized to perform this operation.
    at Request.extractError (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/cloud-reports/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'You are not authorized to perform this operation.',
  code: 'UnauthorizedOperation',
  time: 2020-02-18T23:38:32.201Z,
  requestId: 'd9eecbb3-59bc-46d0-81ef-9f523f85f8b2',
  statusCode: 403,
  retryable: false,
  retryDelay: 96.02234351548347
}
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at makeFileContents (/home/ec2-user/cloud-reports/dist/scan.js:54:20)
    at scan (/home/ec2-user/cloud-reports/dist/scan.js:91:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cloud-reports@1.4.1 scan: `node dist/scan.js "--module" "ec2"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cloud-reports@1.4.1 scan script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-18T23_38_32_306Z-debug.log

############## DEBUG LOG #################
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/.nvm/versions/node/v13.9.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v13.9.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'scan',
1 verbose cli   '--',
1 verbose cli   '--module',
1 verbose cli   'ec2'
1 verbose cli ]
2 info using npm@6.13.7
3 info using node@v13.9.0
4 verbose run-script [ 'prescan', 'scan', 'postscan' ]
5 info lifecycle cloud-reports@1.4.1~prescan: cloud-reports@1.4.1
6 info lifecycle cloud-reports@1.4.1~scan: cloud-reports@1.4.1
7 verbose lifecycle cloud-reports@1.4.1~scan: unsafe-perm in lifecycle true
8 verbose lifecycle cloud-reports@1.4.1~scan: PATH: /root/.nvm/versions/node/v13.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ec2-user/cloud-reports/node_modules/.bin:/root/.nvm/versions/node/v13.9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle cloud-reports@1.4.1~scan: CWD: /home/ec2-user/cloud-reports
10 silly lifecycle cloud-reports@1.4.1~scan: Args: [ '-c', 'node dist/scan.js "--module" "ec2"' ]
11 silly lifecycle cloud-reports@1.4.1~scan: Returned: code: 1  signal: null
12 info lifecycle cloud-reports@1.4.1~scan: Failed to exec scan script
13 verbose stack Error: cloud-reports@1.4.1 scan: `node dist/scan.js "--module" "ec2"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v13.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v13.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid cloud-reports@1.4.1
15 verbose cwd /home/ec2-user/cloud-reports
16 verbose Linux 4.14.165-133.209.amzn2.x86_64
17 verbose argv "/root/.nvm/versions/node/v13.9.0/bin/node" "/root/.nvm/versions/node/v13.9.0/bin/npm" "run" "scan" "--" "--module" "ec2"
18 verbose node v13.9.0
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 1
22 error cloud-reports@1.4.1 scan: `node dist/scan.js "--module" "ec2"`
22 error Exit status 1
23 error Failed at the cloud-reports@1.4.1 scan script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by koladilip** [comment]
I have pushed debugging information so can you please do `git pull` and run the scan again.

**Comment by nmarchini** [comment]
I ran a pull but says it's up to date. The last commit was 19 hours ago which was before I posted my issue.

**Comment by koladilip** [comment]
Sorry, I pushed to some other internal repo. Now I have pushed here. can you try now?

**Comment by nmarchini** [comment]
Thanks for the debugging, I can now see that it's failing on specific regions that I don't have access to (SCP in place now has blocked me). Is there any way we can add a region or list of regions as a parameter when executing the command or is it a case of just editing the /utils/aws/regions_data.ts file each time?

`[ERROR] aws.resourcegroups.ResourceGroupsCollector failed Error: AccessDeniedException:User: arn:aws:sts::216849691610:assumed-role/lon-ec2-default/i-0d07d2be70730261e is not authorized to perform: resource-groups:ListGroups on resource: arn:aws:resource-groups:ap-south-1:216849691610:/groups-list with an explicit deny [
  {
    "us-east-2": "us-east-2",
    "us-east-1": "us-east-1",
    "us-west-1": "us-west-1",
    "us-west-2": "us-west-2",
    "ap-south-1": "ap-south-1"
  }
]`

**Comment by koladilip** [comment]
For that we need to add custom logic. Let me get back to you. Also you are keen to send on this then you can also send a pull request for it.

Thanks,
Dilip
Tensult
________________________________

**Comment by koladilip** [comment]
Add new option to scan for running only for specified regions:
-r ap-south-1,ap-southeast-1
